[package]
name = "pyin_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rustfft = "6"
log = "0.4"
env_logger = "0.11"
symphonia = { version = "0.5", default-features = true }
flutter_rust_bridge = "2"

[dev-dependencies]
rand = "0.8"
